- hosts: all
  gather_facts: false
  tasks:
    - name: Include common variables
      include_vars: common.yml
    - debug:
        msg: "{{ log_path }}"

    - name: ping
      ping:
      register: result

    - name: debug result
      debug:
        msg: "{{ result }}"

    - include_role:
        name: servers
      vars:
        install_httpd: true
